### ISSUE TITLE
Clash checking

### ISSUE THREAD

**Issue by premkrishnaa** [vignesh-m/real-office#43]
Check whether start and end are after curr date/time? also end strictly > start..
![screenshot from 2017-04-09 00-32-45](https://cloud.githubusercontent.com/assets/9005722/24831689/441a8974-1cbc-11e7-8618-0793fe022d76.png)

tried this around 12:30 AM. Both the above conditions are violated..

**Comment by premkrishnaa** [comment]
Oh and it was also clashing with another meeting which was from the previous day.
![screenshot from 2017-04-09 00-38-16](https://cloud.githubusercontent.com/assets/9005722/24831716/db8b4582-1cbc-11e7-82d4-e2a234bc040b.png)

**Comment by premkrishnaa** [comment]
strictly >  part done

**Comment by vignesh-m** [comment]
i guess before current date is fine
